development:
  adapter: postgresql
  encoding: unicode
  database: newspap_bd
  pool: 5
  username: postgres 
  password: postgres 
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: newspap_bd
  pool: 5
  username: postgres 
  password: postgres 
  host: localhost
  port: 5432 
